package com.example.clinic_appointment.utilities;

public class Constants {
    public static final String KEY_NAME = "name";
    public static final String KEY_USER_ROLE = "userRole";
    public static final String KEY_ACCESS_TOKEN = "accessToken";
    public static final String KEY_REFRESH_TOKEN = "refreshToken";
    public static final String KEY_CURRENT_NAME = "currentName";
    public static final String KEY_CURRENT_PHONE_NUMBER = "currentPhoneNumber";
    public static final String KEY_CURRENT_EMAIL = "currentEmail";
    public static final String DOMAIN_LOCAL_HOST = "localhost";
    public static final String PATH_SLASH = "/";
    public static final String HEADER_AUTHORIZATION = "Authorization";
    public static final String HEADER_SET_COOKIE = "Set-Cookie";
    public static final String REGEX_SEMICOLON = ";";
    public static final String KEY_NEW_ACCESS_TOKEN = "newAccessToken";
    public static final String KEY_HEALTH_FACILITY = "healthFacility";
    public static final String KEY_DEPARTMENT = "department";
    public static final String KEY_DOCTOR = "doctor";
    public static final String KEY_DETAIL_DOCTOR = "Doctor";
    public static final String KEY_DATE = "date";
    public static final String KEY_TIME = "time";
    public static final String KEY_PAYMENT_METHOD = "paymentMethod";
    public static final String KEY_ACTION = "action";
    public static final String ACTION_LOOKUP = "lookup";
    public static final String KEY_BOOKING = "booking";
    public static final String KEY_CURRENT_UID = "uid";
    public static final String KEY_STATUS = "status";
    public static final String STATUS_PROCESSING = "Đang xử lý";
    public static final String GENDER_MALE_ENG = "MALE";
    public static final String GENDER_FEMALE_ENG = "FEMALE";
    public static final String KEY_SOURCE_ACTIVITY = "sourceActivity";
    public static final String KEY_START_DATE = "startDate";
    public static final String KEY_END_DATE = "endDate";
    public static final String KEY_SELECTED_ITEM = "selectedItem";
    public static final String KEY_IMAGES = "images";
    public static final String KEY_ITEM_TYPE = "itemType";
    public static final String RETURN_TYPE = "returnType";
    public static final String TYPE_HOSPITAL = "typeHospital";
    public static final String TYPE_DEPARTMENT = "typeDepartment";
    public static final Integer RESULT_ALL_MATCH = 999;
    public static final String KEY_STATUS_CODE = "statusCode";
}
